[package]
name = "polkadot-rpc"
version = "0.7.32"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
jsonrpc-core = "14.0.3"
polkadot-primitives = { path = "../primitives" }
sc-client-api = { git = "https://github.com/mxinden/substrate", branch = "network-gossip-bounded"  }
sp-blockchain = { git = "https://github.com/mxinden/substrate", branch = "network-gossip-bounded"  }
sp-runtime = { git = "https://github.com/mxinden/substrate", branch = "network-gossip-bounded"  }
sp-api = { git = "https://github.com/mxinden/substrate", branch = "network-gossip-bounded"  }
sc-rpc = { git = "https://github.com/mxinden/substrate", branch = "network-gossip-bounded" }
sc-finality-grandpa = { git = "https://github.com/mxinden/substrate", branch = "network-gossip-bounded" }
sc-finality-grandpa-rpc = { git = "https://github.com/mxinden/substrate", branch = "network-gossip-bounded" }
txpool-api = { package = "sp-transaction-pool", git = "https://github.com/mxinden/substrate", branch = "network-gossip-bounded" }
frame-rpc-system = { package = "substrate-frame-rpc-system", git = "https://github.com/mxinden/substrate", branch = "network-gossip-bounded"  }
pallet-transaction-payment-rpc = { git = "https://github.com/mxinden/substrate", branch = "network-gossip-bounded" }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false }
