[package]
name = "polkadot-service"
version = "0.7.2"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parking_lot = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.8"
futures = "0.3.1"
futures01 = { package = "futures", version = "0.1.29" }
slog = "2.5.2"
hex-literal = "0.2.1"
av_store = { package = "polkadot-availability-store", path = "../availability-store" }
consensus = { package = "polkadot-validation", path = "../validation" }
polkadot-primitives = { path = "../primitives" }
polkadot-runtime = { path = "../runtime" }
polkadot-executor = { path = "../executor" }
polkadot-network = { path = "../network"  }
polkadot-rpc = { path = "../rpc" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
primitives = { package = "sp-core", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
client = { package = "sc-client", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
client-api = { package = "sc-client-api", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
client-db = { package = "sc-client-db", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
consensus_common = { package = "sp-consensus", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
grandpa = { package = "sc-finality-grandpa", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
grandpa_primitives = { package = "sp-finality-granpda", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
inherents = { package = "sp-inherents", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
service = { package = "sc-service", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test", default-features = false }
telemetry = { package = "sc-telemetry", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
txpool = { package = "sc-transaction-pool", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
txpool-api = { package = "sp-transaction-pool-api", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
pallet-babe = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "ashley-update-exit-future-test" }
pallet-staking = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "ashley-update-exit-future-test" }
im-online = { package = "pallet-im-online", git = "https://github.com/paritytech/substrate", default-features = false, branch = "ashley-update-exit-future-test" }
authority-discovery = { package = "sc-authority-discovery", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
authority-discovery-primitives = { package = "sp-authority-discovery", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
babe = { package = "sc-consensus-babe", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future-test" }
babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/paritytech/substrate", default-features = false, branch = "ashley-update-exit-future-test" }

[features]
default = ["rocksdb"]
rocksdb = ["service/rocksdb"]
