[package]
name = "polkadot-service"
version = "0.7.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parking_lot = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.8"
futures = "0.3.1"
futures01 = { package = "futures", version = "0.1.29" }
slog = "2.5.2"
hex-literal = "0.2.1"
av_store = { package = "polkadot-availability-store", path = "../availability-store" }
consensus = { package = "polkadot-validation", path = "../validation" }
polkadot-primitives = { path = "../primitives" }
polkadot-runtime = { path = "../runtime" }
polkadot-executor = { path = "../executor" }
polkadot-network = { path = "../network"  }
polkadot-rpc = { path = "../rpc" }
sr-io = { git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
sr-api = { git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
sr-primitives = { git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
client-api = { package = "substrate-client-api", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
client-db = { package = "substrate-client-db", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
substrate-executor = { git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
substrate-network = { git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
consensus_common = { package = "substrate-consensus-common", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
grandpa = { package = "substrate-finality-grandpa", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
grandpa_primitives = { package = "substrate-finality-grandpa-primitives", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
inherents = { package = "substrate-inherents", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
service = { package = "substrate-service", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future", default-features = false }
telemetry = { package = "substrate-telemetry", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
txpool = { package = "sc-transaction-pool", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
txpool-api = { package = "sp-transaction-pool-api", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
substrate-keystore = { git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
pallet-babe = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "ashley-update-exit-future" }
pallet-staking = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "ashley-update-exit-future" }
im-online = { package = "pallet-im-online", git = "https://github.com/paritytech/substrate", default-features = false, branch = "ashley-update-exit-future" }
authority-discovery = { package = "substrate-authority-discovery", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
authority-discovery-primitives = { package = "substrate-authority-discovery-primitives", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
babe = { package = "substrate-consensus-babe", git = "https://github.com/paritytech/substrate", branch = "ashley-update-exit-future" }
babe-primitives = { package = "substrate-consensus-babe-primitives", git = "https://github.com/paritytech/substrate", default-features = false, branch = "ashley-update-exit-future" }

[features]
default = ["rocksdb"]
rocksdb = ["service/rocksdb"]
