[package]
name = "polkadot-cli"
version = "0.7.9"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Polkadot node implementation in Rust."
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.8"
tokio = "0.2.1"
futures = { version = "0.3.1", features = ["compat"] }
futures01 = { package = "futures", version = "0.1.29" }
structopt = "0.3.4"
cli = { package = "sc-cli", git = "https://github.com/paritytech/substrate", branch = "ashley-polkadot-wasm" }
service = { package = "polkadot-service", path = "../service", default-features = false }

sc-browser = { package = "sc-browser", git = "https://github.com/paritytech/substrate", branch = "ashley-polkadot-wasm", optional = true }
substrate-service = { package = "sc-service", git = "https://github.com/paritytech/substrate", branch = "ashley-polkadot-wasm", optional = true, default-features = false }
wasm-bindgen = { version = "0.2.55", optional = true }
wasm-bindgen-futures = { version = "0.4.5", optional = true }

[features]
default = [ "wasmtime", "rocksdb" ]
wasmtime = [ "cli/wasmtime" ]
rocksdb = [ "service/rocksdb" ]
browser = [
	"sc-browser",
	"wasm-bindgen",
	"wasm-bindgen-futures",
	"substrate-service",
]
