[package]
name = "polkadot-cli"
version = "0.7.13"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Polkadot node implementation in Rust."
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.8"
futures = { version = "0.3.1", features = ["compat"] }
futures01 = { package = "futures", version = "0.1.29" }
structopt = "=0.3.7"
cli = { package = "sc-cli", git = "https://github.com/paritytech/substrate", branch = "ashley-browser-utils" }
service = { package = "polkadot-service", path = "../service", default-features = false }

wasm-bindgen = { version = "0.2.55", optional = true }
wasm-bindgen-futures = { version = "0.4.5", optional = true }
browser-utils = { package = "browser-utils", git = "https://github.com/paritytech/substrate", branch = "ashley-browser-utils", optional = true }
substrate-service = { package = "sc-service", git = "https://github.com/paritytech/substrate", branch = "ashley-browser-utils", optional = true, default-features = false }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
tokio = "0.1.22"

[features]
default = [ "wasmtime", "rocksdb" ]
wasmtime = [ "cli/wasmtime" ]
rocksdb = [ "service/rocksdb" ]
browser = [
	"wasm-bindgen",
	"wasm-bindgen-futures",
	"browser-utils",
	"substrate-service",
]
